### ISSUE TITLE
Release v2.0

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#2063]
Okay, so I realise I've been somewhat absent recently. My current job ends on September 12th and my next one doesn't start until late November, so I plan to get v2.0 out the door during that period of time. I promise I will wade through the back log of PRs that have built up :+1:

**Comment by jamesmckinna** [comment]
Congratulations on the new job! 🎉

**Comment by jamesmckinna** [comment]
As to managing the backlog, as both a contributor to making the pile grow, as well as more recently, helping to whittle it down (at least a little bit), I was interested to read that our colleagues on the main Agda issue tracker are correspondingly [concerned about their own policies to manage their PR backlog](https://github.com/agda/agda/issues/6482). 

It might be worth a separate issue, but rather than generate more clutter, I'm linking it here while our efforts are directed towards the v2.0 backlog... once that's out, suggest we (re)start the conversation about how to manage the way forward.

**Comment by MatthewDaggitt** [comment]
Okay, with the merge of https://github.com/agda/agda-stdlib/pull/1895 I'm going to get serious about making a release. 

As of now, all new PRs will get a v2.1 milestone unless they explicitly address an issue that needs to be fixed before v2.0. 

Existing open PRs will be triaged depending on how easy they are to merge.

When would interested people be available for a meeting next week to discuss outstanding PRs? If you are, please state your availability in GMT below:

Matthew
- Monday 2nd - 7am - 4pm 
- Tuesday 3rd - 7am - 11am, 2pm-4pm
- Wednesday 4th - 7am - 4pm
- Thursday 5th - 7am - 4pm
- Friday 6th - 7am - 11am

**Comment by Taneb** [comment]
My availabilities next week:

* Monday 6-7am, 7:30-9am, 10:30am-late
* Tuesday 6-7am, 8am-12pm, 2pm-late
* Wednesday 6-7am, 7:30am-late
* Thursday 6-7am, 7:30am-12pm, 2pm-late
* Friday 6-7am, 7:30am-12pm, 1:30pm-late

**Comment by jamesmckinna** [comment]
This is great news! 

As for a meeting next week, I'm a bit all over the place at the moment, as evidenced by the manic PR/issue/commentary explosion. Will try to identify times to meet soon! 

I've been working on 'one last' (sic) branch for the `AlmostCancellative` issues (the corresponding ones for `Monotonic` can wait, but it might be good to try to knock those off as well), so I hope we can merge that/them. But: up for discussion ;-)

**Comment by JacquesCarette** [comment]
Next week is tricky for me: the good part, I'll be in Europe, so time zones less of an issue; less good from an availability perspective: I'll be in Dagstuhl. So while it is quite likely that I could get out for an hour, knowing when that'll be is essentially impossible to know now.

So: schedule it, and I'll see.

**Comment by jamesmckinna** [comment]
I'll be largely free-but-frazzled next week, so let me know when works best for you and @Taneb , and let's see how we do...

**Comment by MatthewDaggitt** [comment]
Okay, let's go for Wednesday 7:30am GMT then. Whoever is around is welcome to join.

**Comment by MatthewDaggitt** [comment]
Meeting link here: https://meet.google.com/trh-fpbj-kfi

**Comment by jamesmckinna** [comment]
Not really a separate issue, but to note here: before release, we should nitpick the `CHANGELOG` to satisfy ourselves it makes global as well as local sense (orphaned/duplicated comments; list of deprecations/additions getting out of alphabetical/file contents order, spellcheck, fix-whitespace, ...)

**Comment by Taneb** [comment]
https://time.is/730_4_Oct_2023_in_UTC

**Comment by MatthewDaggitt** [comment]
> Not really a separate issue, but to note here: before release, we should nitpick the CHANGELOG to satisfy ourselves it makes global as well as local sense (orphaned/duplicated comments; list of deprecations/additions getting out of alphabetical/file contents order, spellcheck, fix-whitespace, ...)

Yup, that's always necessary before a release! I usually do it as the last possible thing though, otherwise you get horrendous merge conflicts with open PRs.

**Comment by MatthewDaggitt** [comment]
There is another meeting today at https://time.is/1200_12_Oct_2023_in_UTC. Same link. @laMudri would you be available to join briefly to discuss https://github.com/agda/agda-stdlib/pull/2054 and another related issue?

**Comment by laMudri** [comment]
Should be able to, yeah. :+1:

**Comment by MatthewDaggitt** [comment]
Still 20 open issues and PR for v2.0 to go.

**Comment by jamesmckinna** [comment]
Have all the decisions we made this week and last been carried across to the milestone, specifically those triage decisions to move things to v2.1/v3.0, eg IIRC
* $\mapsto$  v2.1
- [ ] #1511 (unless someone else volunteers to fix this up)
- [ ] #1579 ? (it would be nice to have got this done in time, but ... related to #1436 , #1562 which got bumped to v3.0)
- [ ] #1825 ? (ditto.)
- [ ] #2098 (unless you are committed to getting it done now?)
* $\mapsto$  v3.0
- [ ] #759 this seems to be a recurrent one, mostly for Matthew's shopping list which perhaps needs updating to show the current state of this issue and the associated PRs?
- [ ] #31 the discussion here seems never to have led to a concrete decision/PR (much like #278)

That still leaves a chunk of work to do, but maybe the end is then in sight?

**Comment by MatthewDaggitt** [comment]
> #1579 ? (it would be nice to have got this done in time, but ... related to #1436 

This has to be bumped to 3.0 as again it's breaking. But you're right, we don't have the energy to do it now.

> #2098 (unless you are committed to getting it done now?)

This can't be bumped to v2.1 as it's going to be massive breaking change. So yes, relatively committed, and the `StrictTotalOrder` refactor was in preparation for it.

> #759 this seems to be a recurrent one, mostly for Matthew's shopping list which perhaps needs updating to show the current state of this issue and the associated PRs?

So this one, I'm going through deprecating each individual definition as well, as they've been scattered across many different modules. It also helps to check that we've actually got everything in the new hierarchy.


The rest are bumped as you suggested.

**Comment by MatthewDaggitt** [comment]
Down to 12 open issues/PRs....

**Comment by MatthewDaggitt** [comment]
Every open `v2.0` issue now has a PR open fixing it. If everyone could do a quick review of one or two of the PRs each, then we can hopefully get a candidate release out by the end of the week.

**Comment by MatthewDaggitt** [comment]
Release candidate 1 created and announced. Waiting for the flood of issues in 3... 2... 1...

Other than that, thank you to everyone who has helped get it over line!

**Comment by shhyou** [comment]
Is it possible to resolve #1743 so users can open README[/*].agda files? It could be changing how README[/*].agda modules are packaged in the release tarball or adding instructions to installation guide, whichever is more convenient.

**Comment by MatthewDaggitt** [comment]
> Is it possible to resolve https://github.com/agda/agda-stdlib/issues/1743 so users can open README[/＊].agda files? It could be changing how README[/＊].agda modules are packaged in the release tarball or adding instructions to installation guide, whichever is more convenient.

Okay, will do our best.

**Comment by MatthewDaggitt** [comment]
Would some subset of people be free for a meeting on Tuesday or Thursday this week? To discuss issues that have popped up with v2.0 and I guess moving forwards!

**Comment by jamesmckinna** [comment]
Either works for me.

**Comment by JacquesCarette** [comment]
Both can work for me.

**Comment by jamesmckinna** [comment]
Apologies, sort of, for having added a couple of purely bureaucratic PRs #2205 , #2206  to the pile. 
But hopefully they are/will be easy to review/merge..

**Comment by MatthewDaggitt** [comment]
Okay every open issue with v2.0 on it has a corresponding open PR. So if people could take a look and try and review them we can make the next RC by the start of next week hopefully.

**Comment by jamesmckinna** [comment]
Regarding the release: what becomes of the the v1.* deprecation warnings everywhere in the library?
Should be be systematically removing them now, given the massive step-change to v2.0? 
What's the policy generally about such things?

**Comment by MatthewDaggitt** [comment]
So as part of v2.0 I [removed](https://github.com/agda/agda-stdlib/blob/master/CHANGELOG.md#removed-deprecated-names) all deprecated content before v1.2.

I don't think we want to remove all v1.* deprecated content as some of it was deprecated relatively recently... but I have no formal policy. I chose v1.2 as it got rid of a **lot** of empty deprecated modules.

**Comment by MatthewDaggitt** [comment]
Announced release candidate 2.

**Comment by jamesmckinna** [comment]
Sigh... our first new issue #2216 ... :-(

**Comment by jamesmckinna** [comment]
Should be good to go now!

**Comment by MatthewDaggitt** [comment]
Okay announced the release. I am however struggling to follow the instructions to generate the documentation. 

In particular:
```
    cp .github/tooling/* .
    runhaskell GenerateEverything.hs
    ./index.sh
    agda -i. -idoc -isrc --html index.agda
    mv html v$VERSION
    git checkout gh-pages
    git add v$VERSION/*.html v$VERSION/*.css
    git commit -m "[ release ] doc for version $VERSION"
    git push
```
on the `runhaskell` step I'm getting
```
GenerateEverything.hs:19:1: error:
    Could not find module ‘System.FilePath.Find’
    Perhaps you meant
      System.FilePath.Windows (from filepath-1.4.2.2)
      System.FilePath.Windows
      System.FilePath (from filepath-1.4.2.2)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
19 | import System.FilePath.Find
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I've run `cabal install` in the directory but still no luck. @jamesmckinna did you come across this issue last time?

**Comment by Taneb** [comment]
That module looks like it should come from the `filemanip` package.

**Comment by MatthewDaggitt** [comment]
Yup, but shouldn't `cabal install` get it for me? I'm not even sure how to go about installing random packages on my system from Hackage, outside of `cabal` and `stack`...

**Comment by jamesmckinna** [comment]
No, I don't seem to have come across this before. 

Indeed, I recently upgraded on one machine finally to 2.6.4, and IIRC, that installed `filemanip` for me...?

Obvious addition: run `cabal update` and then ask for the latest `cabal` as well. Again, IIRC, upgrading my `ghc` with `ghcup` also may have helped with all of the above, esp. wrt identifying 'stable'/'recommended' versions of packages. 

All of the above aside, I am a total n00b when it comes to these things... but I'll (try to) check when I'm back home tonight.

**Comment by jamesmckinna** [comment]
Also: #2226  I'm not currently at a machine where I can easily fix this...

**Comment by MatthewDaggitt** [comment]
Okay, great. I've managed to upload the documentation. Thanks for your help @Taneb!
