### ISSUE TITLE
Overhaul of `Data.X.Categorical`

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#365]
So far we only have monad instances in:

* [x] Data.List.Categorical
* [x] Data.List.NonEmpty
* [x] Data.Maybe
* [x] Data.Sum.Categorical (coming up, #361)
* [x] Data.Product.Categorical (coming up, #378)
* [x] Add `RawMonadT` as an alias?

Bonus points: zippy applicatives for

* [x] Codata.Delay 
* [x] Codata.Stream
* [x] Codata.Colist
* [x] Codata.Covec
* [x] Data.Vec
* [x] Data.Product.N-ary
* [x] Add Identity Applicative (cf #396)
* [x] Cleanup [`lookup-morphism`](https://agda.github.io/agda-stdlib/Data.Vec.Categorical.html#2251) using Identity Applicative

Bonus bonus points: comonad instances for

* [x] Category.Comonad.Identity
* [x] Codata.Stream
* [x] Data.List.NonEmpty
* [x] Data.Product

Bonus^3 points:

To be able to define these notions as records, we would need to have level-polymorphic fields i.e. we would need a type for `Set omega`.

~~* [ ] introduce foldable~~
~~* [ ] introduce traversable~~
~~* [ ] refactor sequence(A/M), map(A/M), and for(A/M)~~
